### PR TITLE
Refactor telegram, add inline keyboard capability

### PR DESCRIPTION
**Pull request by DanyaSWorlD**

### CODE REVIEW

**Comment by sashausb** [comment]
Need to add checking for miscliks.

**Review by DogsTailFarmer — CHANGES_REQUESTED** [review]
Hi! Well done, but it is possible to limit this change only to the declared ```def telegram()```, I'm not ready to explore reformatting the whole code at the moment, sorry.
Regard's, Jerry.

**Comment by DanyaSWorlD** [comment]
@DogsTailFarmer That's should be better

**Comment by DogsTailFarmer** [comment]
> 

Yes, is the right time to do this, for version 1.2.7 changes will be made to the configuration file, you can add this parameter now.

**Review by DogsTailFarmer — APPROVED** [review]

**Pull request merged**
